### ISSUE TITLE
Check service users in Kio not in services api

### ISSUE THREAD

**Issue by Traumeel** [zalando-stups/friboo#41]
So applications, which belong to virtual teams, are not recognized as being owned by the 'main' team.

https://github.com/zalando-stups/friboo/blob/master/src/org/zalando/stups/friboo/user.clj#L71

**Comment by prayerslayer** [comment]
To elaborate on the underlying problem: App `creator` associated to "team" (actually account) `foo` has `application.write` scope and wants to, well, create applications. When it tries to do so, Kio refuses because `creator` belongs to team (like, real team) `bar`, which owns account `foo` => `foo != bar`.

Not sure yet if this is to be fixed in Friboo or just Kio.

**Comment by prayerslayer** [comment]
I think it makes sense to fix this in Friboo as the same problem arises in `mint-storage`.
